dataset_mapping:
  counsel_chat:
    - CounselChat https://github.com/nbertagnolli/counsel-chat
    - 
  amod_counseling_conversations:
    - Amod Mental health counseling conversations https://huggingface.co/datasets/Amod/mental_health_counseling_conversations From Huggingface description: This dataset is a collection of real counselling question-and-answer pairs taken from two public mental-health platforms. It is intended for training and evaluating language models that provide safer, context-aware mental-health responses.
    - "Huggingface: Mental Health Counseling Conversations
https://huggingface.co/datasets/Amod/mental_health_counseling_conversations"
  psy_qa:
    - |
      PsyQA is an authoritative Chinese dialogue dataset focused
      on the field of mental health support. It covers 9 broad
      topics and multiple subtopics, encompassing various aspects
      of mental health. PsyQA is presented in a question-answer
      format, where each example includes a question, a detailed
      description of the mental issues, and keywords provided by
      anonymous help-seekers. Responses are asynchronously pro-
      vided by well-trained volunteers or professional counselors
      and involve detailed analysis and guidance in response to the
      help-seekers’ questions, aiming to offer mental health support.
      Additionally, the answers have been further annotated with
      seven psychological strategies based on psychological coun-
      seling theory [12],
    - PsyQA, extended by "helping skills" column
    - 1,000 QA pairs from the PsyQA dataset.  two human annotators inspected and labeled the responses of professional supporters in the PsyQA dataset with the corresponding professional psychological counseling theory categories (Cognitive-Behavioral Therapy labeled as 1, Dialectical Behavior Therapy as 2, Person-Centered Therapy as 3, and Reality Therapy as 4). The original data had quantities of 189, 317, 196, and 298 for categories 1, 2, 3, and 4, respectively.
  alexander_street_press:
    - |
      fine-tuned on the 2 volumes of published counseling and psychotherapy data from
      Alexander Street Press. The volumes are searchable collections of transcripts containing real counseling and therapy sessions
      and first-person narratives illuminating the experience of mental illness and treatment. The 2 volumes contain 3500 session transcripts and >700,000 utterances between a counselor and a
      patient.
    - Alexander Street Press therapy transcripts
    - |
      The primary dataset used in this study consists of psychotherapy transcripts from
      https://www.lib.montana.edu/resources/about/677 (accessed on 10 March 2025), the
      “Counseling and Psychotherapy Transcripts, Volume II” dataset.
  empathetic_dialogues:
    - |
      EmpatheticDialogues https://github.com/facebookresearch/EmpatheticDialogues

      From Rashkin et al. [52], containing around 25,000 conversations rooted in emotional situations, with labels for various emotions like sadness, anxiety, and anger.


